### ISSUE TITLE
소수 변환 기능

### ISSUE THREAD

**Issue by joan-KIM** [joan-KIM/calculator#6]

**Comment by ParkEunwoo** [comment]
- 숫자 입력 상태 (음수입력, 소수입력, 양수입력) 보관 및 설정 필요
- 숫자 입력 상태에 따라 숫자버튼 선택시 계산 방식이 바뀜

**Comment by ParkEunwoo** [comment]
소수점 상태에서 backspace 키 눌렀을때 정상 동작 확인 필요
